name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.1.0
  - pydantic=1.8.2
  - pyarrow=2.0
  - pip:
      - mlflow==2.2.2
      - protobuf==3.20.*
      - wandb==0.12.17
      - pipenv==2023.10.24
      - ipykernel==6.26.0
      - matplotlib==3.7
      - hydra-joblib-launcher==1.2.0
      - omegaconf==2.3.0