name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pytest=6.2.2
  - pyarrow=2.0
  - scipy=1.5.2
  - pip=20.3.3
  - pip:
      - mlflow==2.2.2
      - protobuf==3.20.*
      - wandb==0.12.17