name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - mlflow==2.2.2
      - protobuf==3.20.*
      - wandb==0.12.17
      - pipenv==2023.10.24
      - ipykernel==6.26.0
      - hydra-joblib-launcher==1.2.0
      - omegaconf==2.3.0